### ISSUE TITLE
OnlyOffice not taking full screen height

### ISSUE THREAD

**Issue by pReya** [OliverParoczai/nextcloud-unroundedcorners#26] opened 2024-01-13 20:19 UTC
There was an edge case that was mentioned in this post right here: https://github.com/nextcloud/server/issues/34727#issuecomment-1890476489

Would be nice if the author's custom CSS would find its way into this App right here.

**Comment by OliverParoczai** [comment] 2024-01-13 20:29
Hello! I'm looking into it, will update this issue after I do some testing with the rules mentioned above

Thanks,
Oliver

**Comment by OliverParoczai** [comment] 2024-01-14 23:30
Hello!

I installed the OnlyOffice extension and did some testing, but I cannot find any mentions to #onlyofficeFrame while the extension's page is loaded.

The only tag I can find on the iframe that the extension loads has the following css code:
#content.app-onlyoffice #app > iframe {
    height: calc(100vh - 50px);
}
And at least at first glance it seems to do it's job without modifying anything, as the extension's page looks like this to me without any modifications:
![Screenshot_20240115_002439](https://github.com/OliverParoczai/nextcloud-unroundedcorners/assets/14364555/f1523015-1b34-46cb-8ce6-8319a118ef4e)

My current versions are:
Nextcloud 28.0.1
OnlyOffice 9.0.0
Unrounded Corners 1.1.2

Could it be that they fixed it in the newest versions, or maybe I am doing something incorrectly, but I couldn't get it to misbehave. Please let me know how the issue could be reproduced, and I will try doing it

Thanks,
Oliver

**Comment by arnowelzel** [comment] 2024-02-19 14:12
The fix I use here:

```
#onlyofficeFrame {
  height: calc(100vh + 8px);
}
```

**Comment by OliverParoczai** [comment] 2024-04-20 01:56
Hello!

I just got back from a hiatus, and the #onlyofficeFrame fix works for my instance as well, so it will be included in tomorrow's release.

Thanks for the patience, and let me know if there's anything else that I can add/fix.

Best regards,
Oliver

**Closed by OliverParoczai** 2024-04-20 01:56 UTC
